name: admin_template_responsive
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/image/
    - asset/svg/
